### ISSUE TITLE
Tests on Windows fails due to line endings

### ISSUE THREAD

**Issue by Tomalak** [birtles/rikaichamp#505]
Currently (v0.3.3) `yarn test` on Windows leads to a bunch of errors like this:

```
  ● Dictionary › orders words by priority

    SyntaxError: Unexpected token i in JSON at position 0
        at JSON.parse (<anonymous>)

      198 |           }
      199 |
    > 200 |           const entry = JSON.parse(
          |                              ^
      201 |             this.wordDict.substring(offset, this.wordDict.indexOf('\n', offset))
      202 |           ) as RawWordRecord;
      203 |

      at Dictionary.lookupInput (src/data.ts:200:30)
      at Dictionary.wordSearch (src/data.ts:126:31)
      at Object.<anonymous> (src/data.test.ts:318:20)
```

This is caused by offset errors in the `words.ljson` file caused by git converting the line endings during checkout. Amending `.gitattributes` fixes the issue:

```
data/*.dat text eol=lf
data/*.idx text eol=lf
data/*.ljson text eol=lf
```

**Comment by birtles** [comment]
Thank you!
